[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[lib]
name = "chip8"
path = "src/lib.rs"

[[bin]]
name = "chip8"
path = "src/bin/chip8.rs"

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
sdl2 = "0.35.2"

[dev-dependencies]
rstest = "0.15.0"
